ALTER TABLE `Perfume`
  DROP COLUMN `category`,
  ADD COLUMN `description` VARCHAR(191) NULL DEFAULT '',
  ADD COLUMN `genero` ENUM('HOMBRE','MUJER','UNISEX') NOT NULL DEFAULT 'UNISEX',
  ADD COLUMN `isDecant` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `tipo` ENUM('NICHO','ARABES','DISENADOR','OTROS') NULL,
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  MODIFY `images` JSON NULL;

UPDATE `Perfume` SET `tipo` = 'OTROS' WHERE `tipo` IS NULL;

ALTER TABLE `Perfume`
  MODIFY `tipo` ENUM('NICHO','ARABES','DISENADOR','OTROS') NOT NULL;

CREATE INDEX `Perfume_genero_tipo_isDecant_idx`
  ON `Perfume`(`genero`,`tipo`,`isDecant`);
