-- AlterTable
ALTER TABLE `User` ADD COLUMN `passwordHash` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `phone` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `shippingCity` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `shippingNotes` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `shippingRegion` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `shippingStreet` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `shippingZip` VARCHAR(191) NOT NULL DEFAULT '';
